### ISSUE TITLE
Use pytest instead of unittest

### ISSUE THREAD

**Issue by anthonyraf** [anthonyraf/wind-parser#2]
**Implement tests suit with pytest**

**Comment by Njoguu** [comment]
Hello @anthonyraf . I'll be more than happy to work on this!

**Comment by anthonyraf** [comment]
@Njoguu It's done, I assigned you the issue

**Comment by anthonyraf** [comment]
Thanks for your contribution @Njoguu, it makes me happy to experience collaboration on github for the first time.😁
